### ISSUE TITLE
[Small idea] Screenshot variants for the different glimmer-tetris part?

### ISSUE THREAD

**Issue by rubyFeedback** [AndyObtiva/glimmer_tetris#1]
Hey there Andy,

This one is a fairly small-ish suggestion.

Since you have a github page here for glimmer_tetris, how about adding a screenshot variant for all
the different glimmer-dsl's that support tetris?

For instance, for tk, swt, perhaps rails/opal (including perhaps the part of the browser that shows the
URL, so people can know that it works there), libui if that works (just as the proof of concept), gtk -
not sure I forgot one. The idea would be just to showcase where tetris all works. Perhaps the most
important ones may be swt and a web-variant, as that is probably the main target audience (I
think), but I am kind of thinking more as a proof-of-concept in general. After all perhaps glimmer 
may sport a TUI/ncurses interface one day, SDL/gosu, and what not. Or even going wild as a general
DSL not just "limited" to ruby. But anyway, that's the gist idea I had, just a few screenshots if you
have some time come some weekend in the future. Cheers! \o/

(Actually, I believe some projects already have such a screenshot, so you can probably just re-use
these images as-is. Including the one you have for opal/rails I think. So this may really be a small-ish
suggestion.)

**Comment by AndyObtiva** [comment]
This project was created specifically to enable packaging Tetris as a native executable for Mac (DMG) and Windows (MSI) by Glimmer DSL for SWT and to provide an example for how to build Tetris step by step following this Planet Ruby tutorial: 

https://github.com/planetruby/gems/blob/master/glimmer/05-glimmer-tetris-playfield.md

It is not a showcase of Tetris across Glimmer projects, and if people wanted that, they can easily have it in each Glimmer project that supports Tetris. I do not see the point of listing all Tetris variations here. Nobody would care for that. People just want to follow the tutorial provided above and see its code in this repository, then install Tetris on their machine and run it.

I do not see this as a true need for the community, so I am closing this comment (regardless of how easy or not it might be to address since it would muddy the waters to include non-SWT versions of Tetris here).

That said, given that Glimmer Wordle was not created as a code sample for a tutorial, I can do what you want over there by re-implementing it in various Glimmer DSLs for differnet GUI toolkits in the same repository.
